Repository AY2122S1-CS2103T-F11-2/tp, pull requests merged in 2021-11, with the labels that each got.

#296 Change email regex to be more strict to ensure most emails are safe and valid
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Email.java
  src/test/java/seedu/address/model/person/EmailTest.java
Labels: bug

#297 Modify `isSamePerson`
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: documentation, enhancement, testing

#294 Modify UG to fix documentation errors
  docs/UserGuide.md
Labels: bug, documentation

#301 Fix interview invalid date bug, update interview and experience in UG
  docs/UserGuide.md
  src/main/java/seedu/address/model/interview/Interview.java
Labels: bug, documentation, mustfix

#300 Change year of experience to double, with restriction of 1 d.p.
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/person/Experience.java
  src/main/java/seedu/address/model/person/ExperienceContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/model/person/ExperienceTest.java
Labels: enhancement, good-to-fix

#289 Add FindCommand and Interview Datetime implementation details in DG
  docs/DeveloperGuide.md
  docs/diagrams/FindCommandActivityDiagram.puml
  docs/diagrams/FindCommandSequenceDiagram.puml
  docs/images/FindCommandActivityDiagram.png
  docs/images/FindCommandSequenceDiagram.png
Labels: documentation, priority.Medium

#291 Fix Done status changes after editing bug
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: bug, priority.High

#305 Fix unintended mark / unmark command behaviou
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/MarkingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: bug, priority.Medium, good-to-fix

#295 Disallow duplicate indexes and updated UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkingCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: bug, documentation, priority.High

#307 Fix PED UG Issues
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/PrefixSyntax.java
Labels: documentation, priority.Medium

#309 Fix mark and unmark PED bug
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/done/Done.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: bug, priority.High

#310 Update interview message constraints
  src/main/java/seedu/address/model/interview/Interview.java
Labels: bug, documentation, priority.Medium

#311 Update UG based on PE bugs
  docs/UserGuide.md
Labels: documentation, priority.Low

#313 Add design consideration for Filter Interview command
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#317 Add unmark command documentation to DG
  docs/DeveloperGuide.md
  docs/diagrams/UnmarkCommandActivityDiagram.puml
  docs/diagrams/UnmarkCommandSequenceDiagram.puml
  docs/images/UnmarkCommandActivityDiagram.png
  docs/images/UnmarkCommandSequenceDiagram.png
Labels: documentation, priority.High

#287 Update filter interview in DG
  docs/DeveloperGuide.md
  docs/diagrams/FilterInterviewCommandSequenceDiagram.puml
  docs/images/FilterInterviewCommandSequenceDiagram.png
Labels: documentation, priority.Medium

#308 Add `EditCommand` and `AddCommand` implementation details in DG
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandActivityDiagram.puml
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/diagrams/EditCommandActivityDiagram.puml
  docs/diagrams/EditCommandSequenceDiagram.puml
  docs/diagrams/FindCommandSequenceDiagram.puml
  docs/images/AddCommandActivityDiagram.png
  docs/images/AddCommandSequenceDiagram.png
  docs/images/EditCommandActivityDiagram.png
  docs/images/EditCommandSequenceDiagram.png
  docs/images/FindCommandSequenceDiagram.png
  docs/images/ShowCommandSequenceDiagram.png
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: documentation, priority.Medium

#326 Fix broken anchor links and change link to Java 11 download
  docs/UserGuide.md
  docs/images/JavaDownload.png
Labels: documentation, priority.High

#329 Branch ppp (Yao Yi)
  docs/team/pulpy-y.md
Labels: documentation

#335 Add Glossary, Basic Command Format & RecruitIn Icon
  docs/UserGuide.md
  docs/images/RecruitIn.png
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/RecruitIn.png
  src/main/resources/images/address_book_32.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: documentation, priority.High

#340 PPP - Kaushik
  docs/team/kaushikkrdy.md
Labels: documentation, priority.Medium

#339 Draft PPP - Wei Jie
  docs/team/tohweijie01.md
Labels: documentation, priority.Medium

#341 Add PPP
  docs/team/twothicc.md
Labels: documentation, priority.High

#328 Add delete marked command implementation to DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteMarkedCommandActivityDiagram.puml
  docs/diagrams/DeleteMarkedCommandSequenceDiagram.puml
  docs/images/DeleteMarkedCommandActivityDiagram.png
  docs/images/DeleteMarkedCommandSequenceDiagram.png
Labels: documentation, priority.High

#351 Update delete_marked and filter_interview activity diagrams
  docs/diagrams/DeleteMarkedCommandActivityDiagram.puml
  docs/diagrams/FilterInterviewCommandActivityDiagram.puml
  docs/images/DeleteMarkedCommandActivityDiagram.png
  docs/images/FilterInterviewCommandActivityDiagram.png
Labels: bug, documentation, priority.Medium

#337 Minor edits to DG
  docs/DeveloperGuide.md
Labels: documentation, priority.Medium

#348 Add user stories and use cases to DG
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#355 Update UI picture
  docs/images/SampleWorkflow1.png
  docs/images/SampleWorkflow2.png
  docs/images/SampleWorkflow3.png
  docs/images/SampleWorkflow4.png
  docs/images/Ui.png
  docs/images/description.png
Labels: documentation, priority.High

#353 Update UG for find, show, filter_interview and delete features
  docs/UserGuide.md
  docs/images/features/FilterInterviewPast.png
  docs/images/features/Find.png
  docs/images/features/Show.png
Labels: documentation

#352 Update mark, unmark, delete_marked, exit, saving the data file and editing the data file sections to be more reader-friendly
  docs/UserGuide.md
  docs/images/DeleteMarkedAfter.png
  docs/images/DeleteMarkedBefore.png
  docs/images/MarkAfter.png
  docs/images/MarkBefore.png
  docs/images/UnmarkAfter.png
  docs/images/UnmarkBefore.png
Labels: documentation, priority.Medium

#343 Update last few sections of the UG to be more reader-friendly and add `Clear` command
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/EmploymentType.java
  src/main/java/seedu/address/model/person/LevelOfEducation.java
Labels: documentation, priority.High

#347 Change `Add`, `Edit` and `Show` documentation in DG
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandActivityDiagram.puml
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/diagrams/EditCommandActivityDiagram.puml
  docs/diagrams/ShowCommandActivityDiagram.puml
  docs/diagrams/ShowCommandSequenceDiagram.puml
  docs/images/AddCommandActivityDiagram.png
  docs/images/AddCommandSequenceDiagram.png
  docs/images/EditCommandActivityDiagram.png
  docs/images/ShowCommandActivityDiagram.png
  docs/images/ShowCommandSequenceDiagram.png
Labels: documentation, priority.High

#358 Add intro to DG and change links and wording in UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, priority.High

#362 Update DG Table of Contents and Manual Testing
  docs/DeveloperGuide.md
Labels: documentation, priority.Medium

#377 Update DG links
  docs/DeveloperGuide.md
Labels: bug, documentation

#366 Add manual testing for mark, unmark and delete marked in DG
  docs/DeveloperGuide.md
Labels: documentation, priority.Medium

#368 Add design considerations for mark and unmark command in DG
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: documentation, priority.Medium

#360 Update `help`, `add`, `edit` and `list` documentation in UG
  docs/UserGuide.md
  docs/images/AddAfter.png
  docs/images/AddBefore.png
  docs/images/EditAfter.png
  docs/images/EditBefore.png
Labels: documentation, priority.Medium

#367 Edit UG
  docs/UserGuide.md
Labels: documentation, priority.Medium

#372 Add manual test cases in DG for edit, delete and save files
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#380 Fix show tags
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/ShowCommandTest.java
Labels: priority.High, coding quality

#381 UG and DG changes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/features/DeleteAfter.png
  docs/images/features/DeleteBefore.png
  docs/images/features/FilterInterviewAfter.png
  docs/images/features/FilterInterviewBefore.png
  docs/images/features/FilterInterviewPast.png
  docs/images/features/Find.png
  docs/images/features/FindAfter.png
  docs/images/features/FindBefore.png
  docs/images/features/InterviewDisplay.png
  docs/images/features/Show.png
  docs/images/features/ShowAfter.png
  docs/images/features/ShowBefore.png
Labels: documentation

#386 Branch ToC in UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, priority.Medium

#389 Add a few test cases to increase cov for `FindCommandParser` and `Interview`
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/interview/InterviewTest.java
Labels: coding quality

#383 Reduce method length and remove deep nesting
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: priority.High, coding quality

#378 Add manual testing for `show`
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#390 Update PPP
  docs/team/kaushikkrdy.md
Labels: documentation

#399 Update PPP
  docs/team/kaushikkrdy.md
Labels: documentation, priority.Medium

#401 Add acknowledgements and update code links in DG
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
Labels: documentation, priority.High

#407 Add warning against editing preferences.json
  docs/UserGuide.md
Labels: documentation, priority.High

#410 Update PPP - Wei Jie
  docs/team/tohweijie01.md
Labels: documentation, priority.Medium

#412 Update PPP - Chen En
  docs/team/twothicc.md
Labels: documentation, priority.High

#405 Add javadocs and change usage message for show command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/RoleContainsKeywordsPredicate.java
Labels: documentation, priority.High

#408 Refine javadoc and add one assertion in `Interview`
  src/main/java/seedu/address/model/interview/Interview.java
Labels: documentation, coding quality

#419 Update PPP
  docs/team/pulpy-y.md
Labels: documentation

#418 Increase sample data to 20 applicants
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: enhancement, priority.High

#424 Add 20th sample data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium

#425 Update link to app in UG and add about section to DG
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
Labels: documentation, priority.High

#426 About us image
  docs/AboutUs.md
Labels: bug

#414 Add javadocs
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FilterInterviewCommand.java
Labels: documentation, priority.High, coding quality

#430 Update index.md acknowledgements to match DG acknowledgements
  docs/index.md
Labels: documentation, priority.Low

#416 Add `Appendix:Effort` into DG
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#393 Add manual test cases for edit
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#394 Spelling issues in UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, priority.Low

#428 Modify add and edit diagrams
  docs/images/ug-features/AddAfter.png
  docs/images/ug-features/AddBefore.png
  docs/images/ug-features/EditAfter.png
  docs/images/ug-features/EditBefore.png
Labels: bug, documentation, priority.Medium

#409 Add Javadocs
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/MarkingCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/MarkingCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/done/Done.java
  src/main/java/seedu/address/model/done/DoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/notes/Notes.java
  src/main/java/seedu/address/model/notes/NotesContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/LevelOfEducation.java
  src/main/java/seedu/address/model/person/LevelOfEducationContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
Labels: documentation, priority.Medium, coding quality

#432 Add javadocs for EmploymentType
  src/main/java/seedu/address/model/person/EmploymentType.java
  src/main/java/seedu/address/model/person/EmploymentTypeContainsKeywordsPredicate.java
Labels: priority.High

#373 Add PPP - Bryann
  docs/team/bryannyeap.md
  docs/team/johndoe.md
Labels: documentation, priority.High

#439 Remove duplicate PR link
  docs/team/twothicc.md
Labels: documentation
